### ISSUE TITLE
Show us your static website

### ISSUE THREAD

**Issue by alopezag** [alopezag/WT-2020I#1]
While working on your website, you can post here screenshots and the link to your Static Website. 

The idea, it is to share your knowledge with others. So, if someone asks how you do this and that, please be free to answer.

**Comment by alopezag** [comment]
Mi sitio: https://alopezag.github.io/static_website/

<img width="664" alt="Screenshot 2020-05-10 at 16 32 04" src="https://user-images.githubusercontent.com/7943442/81502047-2ff1ff00-92a1-11ea-8bc4-c56174cb8350.png">

**Comment by villacisjulio** [comment]
Profesor estamos probando la configuracion de hugo y nos muestra la pagina pero de los 6 solo a 1 le muestra el tema, podria ayudarnos.

Parece que es un problema en el servidor de github
![error-tema](https://user-images.githubusercontent.com/65053245/81636562-c6c1d700-93d9-11ea-890b-7870872852d2.png)

**Comment by Datorres1234** [comment]
Profesor buenas noches, 
Tenemos la novedad#1 de que no se habilita la opcion: Master branch / docs folder

![image](https://user-images.githubusercontent.com/65080122/81637512-346f0280-93dc-11ea-86c5-17fd10d4b84c.png)

**Comment by Datorres1234** [comment]
Novedad es que localmente si se publica el tema, pero desde servidor de git, solo lee el readme.
Desde local host: OK.
![image](https://user-images.githubusercontent.com/65080122/81637602-5ff1ed00-93dc-11ea-8f83-d63296b72b2e.png)

Desde la web:   :(

![image](https://user-images.githubusercontent.com/65080122/81637649-78fa9e00-93dc-11ea-9a45-c9cdc57b19f1.png)

**Comment by villacisjulio** [comment]
> Novedad es que localmente si se publica el tema, pero desde servidor de git, solo lee el readme.
> Desde local host: OK.
> ![image](https://user-images.githubusercontent.com/65080122/81637602-5ff1ed00-93dc-11ea-8f83-d63296b72b2e.png)
> 
> Desde la web: :(
> 
> ![image](https://user-images.githubusercontent.com/65080122/81637649-78fa9e00-93dc-11ea-9a45-c9cdc57b19f1.png)

Verificar que el archivo config.tom1 no tenga caracteres ocultos.

**Comment by alopezag** [comment]
Respecto su pregunta https://github.com/alopezag/WT-2020I/issues/1#issuecomment-627091896 he abierto un issue #3, explicando las posibles causas. 

Por cierto recuerden que es un actividad en grupo. Al final solo voy a revisar un solo website por grupo.

**Comment by alopezag** [comment]
@Datorres1234 respecto a su pregunta https://github.com/alopezag/WT-2020I/issues/1#issuecomment-627095956 he abierto un nuevo issue #2 explicando las posibles causas.

**Comment by Datorres1234** [comment]
Solución: eliminar repositorio y crear de nuevo paso a paso.
Recomendaciones: el siguiente comando hugo new site static_website --force, debe ejecutarse sobre la ruta donde se encuentra el repositorio.
El siguiente comando : git submodule add https://github.com/budparr/gohugo-theme-ananke.git themes/ananke , ejecutarlo ya dentro de la carpeta static_website.

Con esas observaciones , el sitio web funciona


![image](https://user-images.githubusercontent.com/65080122/81767713-b889be80-949e-11ea-9a58-f4f72d0dc42b.png)

**Comment by jamespesantes007** [comment]
https://kevinrp.github.io/restaurant/

**Comment by amacancelaj** [comment]
Print de los comandos de Hugo ejecutado, para eso previamente descomprimir la descarga de Hugo, y realizar la configuración en el PATH local del Windows 7 en adelante para que funcionen los comandos de Hugo.

![image](https://user-images.githubusercontent.com/6200482/82011254-0981ea00-963a-11ea-9cf9-5d9732195066.png)
