### ISSUE TITLE
Hugo theme does not load when hosting in GitHub Pages

### ISSUE THREAD

**Issue by alopezag** [alopezag/WT-2020I#3]
Estamos probando la configuracion de hugo y nos muestra la pagina pero de los 6 solo a 1 le muestra el tema, podria ayudarnos.

Parece que es un problema en el servidor de github
![error-tema](https://user-images.githubusercontent.com/65053245/81636562-c6c1d700-93d9-11ea-890b-7870872852d2.png)

_Originally posted by @villacisjulio in https://github.com/alopezag/WT-2020I/issues/1#issuecomment-627091896_

**Comment by alopezag** [comment]
Novedad es que localmente si se publica el tema, pero desde servidor de git, solo lee el readme.
Desde local host: OK.
![image](https://user-images.githubusercontent.com/65080122/81637602-5ff1ed00-93dc-11ea-8f83-d63296b72b2e.png)

Desde la web:   :(

![image](https://user-images.githubusercontent.com/65080122/81637649-78fa9e00-93dc-11ea-9a45-c9cdc57b19f1.png)



_Originally posted by Datorres1234 in https://github.com/alopezag/WT-2020I/issues/1#issuecomment-627091896_

**Comment by alopezag** [comment]
Hola @villacisjulio y @Datorres1234

Existen varias razones por las que el Theme podria no mostrarse cuando se despliega el sitio en GitHub Pages. A continuación unas cuantas:

### Theme is not installed
El tema no existe (no a sido descargado localmente). Para eso hay que revisar [Point 5 - Add a theme](https://github.com/alopezag/WT-2020I/issues/3). Sin embargo si este fuera el caso cuando  ejecuten localmente tampoco podrían apreciar el theme. Por lo tanto si les funciona localmente (`hugo server -D`), este no es el problema. 

### Hugo config file 
Revisen la configuración del archivo `config.toml`. [Point 4 - Replace baseURL](https://github.com/alopezag/WT-2020I/blob/master/unit01/activity3/Activity03.md) El parámetro `baseURL` debe incluir la ruta a su repositorio. 
  ```toml
       baseURL = "https://<USERNAME>.github.io/<REPOSITORY-NAME>/"
  ```
  
Por ejemplo, si:
- GitHub username: **Datorres1234** 
- Repository name: **my_repo**

El parametro `baseURL = "https://Datorres1234.github.io/my_repo/`

Pueden encontrar un ejemplo del config file [aquí](https://github.com/alopezag/WT-2020I/blob/master/unit01/activity3/Activity03.md#configuration-file) 

`config.toml` file:
```toml
   baseURL = "https://<USERNAME>.github.io/<REPOSITORY-NAME>/"
   languageCode = "en-us"
   title = "MSIG XXI - My New Hugo Site"
   theme = "ananke"
   publishDir = "docs"
```

- Replace `<USERNAME>` for your actual GitHub username
- Replace `<REPOSITORY-NAME> for your repository name
- `publishDir = "docs"` is mandatory to work on GithHub Project pages

**Recuerden tambien que cualquier cambio en su repositorio local debe hacerse commit y push para que dicho cambio se refleje en el repositorio remoto**

**Comment by villacisjulio** [comment]
Hola Profe efectivamente no estabamos ejecutando hugo -D yo soy del Grupo 1 y mis compañeros son Linda, Karen, Mariella, Omar y Jean.

Todos estamos realizando el trabajo

**Comment by cpanta2020** [comment]
Hola profesor buenas noches, tengo el mismo problema, no me sale la opcion 
![imagen](https://user-images.githubusercontent.com/65083077/81774283-cbf15580-94af-11ea-9e33-ddad9770e479.png)

Y ya segui los pasos del instructivo

**Comment by alopezag** [comment]
Estimado @cpanta2020 revise los comentarios en #2
