### ISSUE TITLE
No se actualiza en el link de la página lo que ingresé en el repositorio

### ISSUE THREAD

**Issue by asantana1970** [alopezag/WT-2020I#5]
Buenos días profesor
tengo un problema , actualicé mi parte en el archivo del repositorio, si salgo que he contribuido pero no se actualiza en el servidor porque cuando abro el link https://mishell27.github.io/static_website/
no me refleja mis cambios. Revisando el historial mis actualizaciones tienen un verified y el de mis compañeros no
![actualizaciones archivo](https://user-images.githubusercontent.com/65082500/81950274-5a0d2f00-95c9-11ea-98e2-9927a5e096c4.png)

**Comment by alopezag** [comment]
Reviso mis comentarios en #4 ?
